project_name: nadctl

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: nadctl
    binary: nadctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: nadctl
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
  name_template: "Release {{ .Tag }}"

brews:
  - repository:
      owner: galamiram
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/galamiram/nadctl"
    description: "Control NAD audio receivers with CLI, TUI, and MCP server for LLM integration"
    license: "MIT"
    test: |
      system "#{bin}/nadctl --help"
    install: |
      bin.install "nadctl"